# install toolchain
before_script: 
- sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa
- sudo apt-get install -y --force-yes gcc-arm-embedded

script: make

# whitelist
branches:
  only:
    - edge
 
